### ISSUE TITLE
偷别人的仓库 然后建群收费 韭菜割的真爽

### ISSUE THREAD

**Issue by fireinrain** [52marvelous/SMSbomb#1]

**Comment by 52marvelous** [comment]
兄弟，眼睛有病就去看看，已经声明了**收费群为广告**，**和项目没关系**。我要是想用这玩意收费根本不需要clone源码，py打包一下想花钱找我的人就多了去了！我想赚这种钱那是随时的事情。你妈的你说你缺心眼不！！！？？？

**Comment by 52marvelous** [comment]
真给你妈杀了
