### ISSUE TITLE
真是你妈的臭傻逼，clone别人的项目，还当成自己开源的。臭傻逼。

### ISSUE THREAD

**Issue by SpanishHuang** [52marvelous/SMSbomb#2]
真是你妈的臭傻逼，clone别人的项目，还当成自己开源的。臭傻逼。
骗钱给你妈烧纸么？你母亲去世了，你在灵棚里骗钱给他下葬是么？臭傻逼。

**Comment by 52marvelous** [comment]
我把你妈杀了，我没说这是我开源的啊，你是个疯狗吧

SpanishHuang ***@***.***> 于2022年7月3日周日 11:14写道：

**Comment by 52marvelous** [comment]
我说是我开源的吗，你妈的你是疯狗吧

**Comment by 52marvelous** [comment]
你妈了傻逼玩意

**Comment by SpanishHuang** [comment]
> 你妈了傻逼玩意

我估计你妈停在灵棚里呢，没钱下葬，来这上面骗点钱下葬。傻逼玩意。还创建群骗钱，真有你的傻逼玩意。祝你妈早点下葬

**Comment by 52marvelous** [comment]
你透过你妈的逼眼儿看到我骗钱了？？？？我群里你进去看了吗？？？？
你妈的傻逼玩意！

**Comment by 52marvelous** [comment]
我真把你妈杀了
